name: Example workflow for Maven using Snyk
on: push
jobs:
  build:
    name: Run Sonar security check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with: 
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Execute Maven verify sonar
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=javareachabilityplayground -Dsonar.organization=artjomsrebrovs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  security:
    name: Run Snyc security check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}        
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan web application
    needs: security
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'  
  run-shell-command:
    runs-on: ubuntu-latest
    name: Run echo command
    needs: zap_scan
    steps:
      - name: Echo status
        run: echo "This workflow is done"        
          
